# Generated by Django 5.2.8 on 2025-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_sosevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicelink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
