# Generated by Django 5.2.8 on 2026-05-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0004_alter_userdevicelink_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosevent',
            name='sos_types',
            field=models.CharField(choices=[('button', 'Button'), ('mpu', 'Mpu'), ('geofencing', 'Geofencing'), ('Dangerzone', 'dangerzone'), ('heart_rate', 'Heart_rate')], default='button', max_length=20),
        ),
    ]
