# Generated by Django 5.2.8 on 2025-11-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
